[2024-05-18T18:53:00.627+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: assignment_dag.dvc manual__2024-05-18T18:42:07+00:00 [queued]>
[2024-05-18T18:53:00.861+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: assignment_dag.dvc manual__2024-05-18T18:42:07+00:00 [queued]>
[2024-05-18T18:53:00.877+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-05-18T18:53:00.879+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2024-05-18T18:53:00.894+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-05-18T18:53:01.203+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): dvc> on 2024-05-18 18:42:07+00:00
[2024-05-18T18:53:01.285+0000] {standard_task_runner.py:55} INFO - Started process 6996 to run task
[2024-05-18T18:53:01.319+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'assignment_dag', 'dvc', 'manual__2024-05-18T18:42:07+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/assignment_dag.py', '--cfg-path', '/tmp/tmppe3sww1r']
[2024-05-18T18:53:01.335+0000] {standard_task_runner.py:83} INFO - Job 22: Subtask dvc
[2024-05-18T18:53:01.975+0000] {task_command.py:376} INFO - Running <TaskInstance: assignment_dag.dvc manual__2024-05-18T18:42:07+00:00 [running]> on host ec7a58f0c94e
[2024-05-18T18:53:03.716+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=i200704@nu.edu.pk
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=assignment_dag
AIRFLOW_CTX_TASK_ID=dvc
AIRFLOW_CTX_EXECUTION_DATE=2024-05-18T18:42:07+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-18T18:42:07+00:00
[2024-05-18T18:53:03.879+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-05-18T18:53:03.887+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd $(dirname /opt/***/output.csv) && dvc add output.csv && dvc commit output.csv -f && dvc push']
[2024-05-18T18:53:04.051+0000] {subprocess.py:86} INFO - Output:
[2024-05-18T18:53:04.218+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dvc: command not found
[2024-05-18T18:53:04.228+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-05-18T18:53:04.311+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-05-18T18:53:04.340+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=assignment_dag, task_id=dvc, execution_date=20240518T184207, start_date=20240518T185300, end_date=20240518T185304
[2024-05-18T18:53:04.457+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 22 for task dvc (Bash command failed. The command returned a non-zero exit code 127.; 6996)
[2024-05-18T18:53:04.558+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-05-18T18:53:04.794+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
